# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ServiceArea.create!(state: 'Alabama', description: 'BigPlanters.com services the entire state of Alabama, including Birmingham, Mobile, Montgomery, Huntsville and Tuscaloosa.')
ServiceArea.create!(state: 'Arizona', description: 'BigPlanters.com services the entire state of Arizona including Phoenix, Tucson, Mesa, Glendale and Scottsdale.')
ServiceArea.create!(state: 'Arkansas', description: 'BigPlanters.com services the entire state of Arkansas including Little Rock, Fort Smith, North Little Rock, Pine Bluff and Jonesboro.')
ServiceArea.create!(state: 'California', description: 'BigPlanters.com services the entire state of California including Los Angeles, San Diego, San Jose, San Francisco, Sacramento, Santa Barbara, Laguna Beach, Oakland, Sonoma, Napa Valley, Silicon Valley, Palo Alto and Monterey.')
ServiceArea.create!(state: 'Colorado', description: 'BigPlanters.com services the entire state of Colorado including Denver, Colorado Springs, Aurora, Lakewood and Fort Collins.')
ServiceArea.create!(state: 'Delaware', description: 'BigPlanters.com services the entire state of Delaware including Wilmington, Dover, Newark, Bethany and Milton.')
ServiceArea.create!(state: 'District Of Columbia', description: 'Our products are ideal for use in government, commercial and healthcare settings and are known throughout the District of Columbia for their high quality and low prices.')

ServiceArea.create!(state: 'Connecticut', description: 'BigPlanters.com services the entire state of Connecticut including Hartford, New Haven, Fairfield, New London, Bridgeport and Meriden.')


ProductGroup.create!(name: 'Concrete Planters', description: 'Our concrete planters come in multiple sizes: 2′, 3′, 4′, 5′, 6′ and 7′. Due to the size and weight of these planters, they provide excellent security barriers while adding to the beauty of commercial properties, parks and recreation areas. Durable construction will hold up well to weather conditions making these planters a practical long-term outdoor showcase for your plants. We offer a variety of colors and finish options to fit your design needs.
If you wish to learn more please feel free to contact our sales support or submit a submission form and we will be happy to assist you in finding the right planter for your project!', image: 'https://www.godawn.com/wp-content/uploads/2016/01/Hotchkiss-Showcase-960x420_c.jpg')

ProductGroup.create!(name: 'Fiberglass Planters', description: 'Our fiberglass planters are a care-free solution to beautifying any indoor or outdoor space by adding an attractive home for your plants. These planters are so popular because they are durable, attractive, light, and functional. Available in a wide variety of vibrant colors and finishes to fit whatever your design needs may be. We also offer a wide range of sizes and styles to fit your design needs.

If you wish to learn more please feel free to contact our sales support or submit a submission form and we will be happy to assist you in finding the right planter for your project!', image: 'https://www.godawn.com/wp-content/uploads/2016/02/Fiberglass-Planters-Header-Image-768x267.jpg')

ProductGroup.create!(name: 'Plastic Planters', description: 'Our plastic planters are extremely durable, their solid construction will hold up well to harsh weather and long term use without showing signs of wear and tear making them perfect for schools, parks, and unsupervised commercial and residential areas. These plastic planters are an eco-friendly alternative to wood or concrete. Recycled plastic planters are a worry-free long-lasting solution for indoor/outdoor decor and all your planting needs.', image: 'https://www.godawn.com/wp-content/uploads/2016/02/Plastic-Planter-Header-Image-768x267.jpg')

ProductGroup.create!(name: 'Metal Planters', description: 'Our metal planters combine design, strength, and durability making them an attractive and long-term solution to your planting needs. We offer many styles, shapes and sizes of metal planters and they are available in many color options to fit your specific design needs.', image: 'https://www.godawn.com/wp-content/uploads/2016/02/Metal-Planter-Main-Pic.jpg')

ProductGroup.create!(name: 'Self Watering Planters', description: 'Dawn Enterprises new “Aqueous” self watering planters looks terrific and are the perfect low-maintenance solution for any planting project indoors or outdoors. Save big $$$ on shipping costs without sacrificing that upscale, permanent appearance. This planter ships at a weight of 13 pounds, yet weighs 300 pounds after planting! Create an attractive perimeter to your property without worrying about a huge freight bill; or losing your new planter to inclement weather. Homeowners, property managers, architects, engineers, landscapers, restaurants, convenience stores, retailers, etc. will love the variety of colors offered.', image: 'https://www.godawn.com/wp-content/uploads/2016/02/Plastic-Planter-Header-Image-768x267.jpg')

ProductGroup.create!(name: 'Tree Tubs', description: 'Our plastic tree tubs are constructed of medium density linear polyethylene. They have UV inhibitors for outdoor use and prolonged life expectancy. The tanks are nestable which aids in reducing shipping costs. The smooth inner surface makes them easy to clean and their lightweight allows for quick set up and relocation. Our tree tubs are great if you would like to have a small garden but have no room in your yard or you have disagreeable soil. These plastic tree tubs come in a variety of colors to fit your design needs.', image: 'https://www.godawn.com/wp-content/uploads/2016/02/Plastic-Planter-Header-Image-768x267.jpg')

ConcretePlanter.create!(product_name: '2ft Cylinder Concrete Planter', price: '$250', description: 'This concrete planter provides a durable and attractive home for your plants. This planter exceeds industrial strength concrete with a minimum rating of 4000 psi at 28 days. Available in a wide variety of colors to fit your design needs.', model: '#PC24x32R', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC24x32R_f.jpg', dimensions: '23.75" dia x 32", 1.5" wall thickness', weight: '435lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', spec: 'https://www.godawn.com/wp-content/uploads/2016/01/PC24x32R.pdf', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '2ft Square Concrete Planter', price: '$250', description: 'This concrete planter make a spacious home for plants of all sizes! Cast with a drain hole and weep channels, you can rest assured your plants will never be harmed by over watering. These concrete planters are available in a variety of colors and finishes to match any decor.', model: '#PC24x24S', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/BP-PC24x24x24S_f.jpg', dimensions: '24" cube x 18" tall with 2" tall x 2" deep toe kick at base', weight: '460lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

ConcretePlanter.create!(product_name: '3ft Round Concrete Deco Base', price: '$300', description: 'Our 3ft round concrete deco base bowl planters make a lovely home for plants of all kinds! Cast with a drain hole and weep channels, you can rest assured your plants will never be harmed by over watering. These concrete planters are available in a variety of colors and finishes to match any decor. Plus, due to their 600 lb weight, they can easily be used as an aesthetically pleasing form of barrier protection.', model: '#PC36RDB', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC36RDB_f.jpg', dimensions: '37.5" Dia. x 20" Height ', weight: '600lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

FiberglassPlanter.create!(product_name: 'Adamas Fiberglass Tall', price: '$206', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIDIT', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAdamas_f.jpg', dimensions: '14" Dia x 24" Height', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red')

FiberglassPlanter.create!(product_name: 'Athens Fiberglass Floor', price: '$120', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIATH', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAthens_f.jpg', dimensions: '14.6" L x 14.6" W x 15.2" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red')

FiberglassPlanter.create!(product_name: 'Athens Tall Fiberglass Planter', price: '$173', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIDITALLFBR', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAthens_Tall_f.jpg', dimensions: '12.8" L x 12.8" W x 26.4" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red')

PlasticPlanter.create!(product_name: 'Aqueous Plastic Self Watering', price: '$99', description: 'The new Aqueous Plastic Self Watering Planter is the perfect, carefree solution to planting indoors or outdoors. The unique design is attractive and allows water to evaporate through the soil so your plants receive the perfect amount of water automatically. Constructed from high density rotationally molded polyethylene these planters are very durable and perfect for outdoor home gardens and commercial applications. Additional colors available, call for more information.', model: '#PP27RSW', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Aqueouslarge_f.jpg', dimensions: '27" Dia x 18" Height', weight: '13lbs')

PlasticPlanter.create!(product_name: 'Round Plastic Oasis Self Watering', price: '$169', description: 'The Oasis self watering planter is constructed of high density rotationally molded polyethylene. Empty, the plastic planter weighs only 20lbs making portability and placement quick and easy. When full, the planter weighs 300 pounds, so it will not disappear from your parking lot. This planter has capillaries between the 25gal water reservoir and the 25gal planting space that allow water to evaporate up into the soil so that your plants get the water they need, when they need it. A small spillway in the planter wall eliminates overwatering.', model: '#PP30RSW', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PP30RSW.jpg', dimensions: '27" Dia x 18" Height', weight: '20lbs')

PlasticPlanter.create!(product_name: 'Brickell Plastic Planter', price: '$119', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#PP30RSW', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Brickell-Group-shot%20(BP).jpeg', dimensions: '27" Dia x 18" Height')

MetalPlanter.create!(product_name: 'Carnival Planter', price: '$549', description: 'The Carnival Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSCRP', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSCRP-P_f.jpg', dimensions: '29.625" Width, 27" Height ', weight: '104lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic')

MetalPlanter.create!(product_name: 'Cunningham Planter', price: '$729', description: 'The Cunningham Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSCNP', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSCNP-P_f.jpg', dimensions: '31.75" Width, 25.125" Height', weight: '167lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic')

MetalPlanter.create!(product_name: 'Genova Planter', price: '$599', description: 'The Genova Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSGNP', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSGNP.jpg', dimensions: '24.875" Width, 17.5" Height ', weight: '144lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic')
