# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ServiceArea.create!(state: 'Alabama', description: 'BigPlanters.com services the entire state of Alabama, including Birmingham, Mobile, Montgomery, Huntsville and Tuscaloosa.')
ServiceArea.create!(state: 'Arizona', description: 'BigPlanters.com services the entire state of Arizona including Phoenix, Tucson, Mesa, Glendale and Scottsdale.')
ServiceArea.create!(state: 'Arkansas', description: 'BigPlanters.com services the entire state of Arkansas including Little Rock, Fort Smith, North Little Rock, Pine Bluff and Jonesboro.')
ServiceArea.create!(state: 'California', description: 'BigPlanters.com services the entire state of California including Los Angeles, San Diego, San Jose, San Francisco, Sacramento, Santa Barbara, Laguna Beach, Oakland, Sonoma, Napa Valley, Silicon Valley, Palo Alto and Monterey.')
ServiceArea.create!(state: 'Colorado', description: 'BigPlanters.com services the entire state of Colorado including Denver, Colorado Springs, Aurora, Lakewood and Fort Collins.')
ServiceArea.create!(state: 'Delaware', description: 'BigPlanters.com services the entire state of Delaware including Wilmington, Dover, Newark, Bethany and Milton.')
ServiceArea.create!(state: 'District Of Columbia', description: 'Our products are ideal for use in government, commercial and healthcare settings and are known throughout the District of Columbia for their high quality and low prices.')

ServiceArea.create!(state: 'Connecticut', description: 'BigPlanters.com services the entire state of Connecticut including Hartford, New Haven, Fairfield, New London, Bridgeport and Meriden.')

ConcretePlanter.create!(product_name: '2ft Cylinder Concrete Planter', price: '$250', description: 'This concrete planter provides a durable and attractive home for your plants. This planter exceeds industrial strength concrete with a minimum rating of 4000 psi at 28 days. Available in a wide variety of colors to fit your design needs.', model: '#PC24x32R', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC24x32R_f.jpg', dimensions: '23.75" dia x 32", 1.5" wall thickness', weight: '435lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', spec: 'https://www.godawn.com/wp-content/uploads/2016/01/PC24x32R.pdf', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '2ft Cylinder With Toe Kick', price: '$250', description: '2ft Cylinder Concrete Planter with Toe Kick - This concrete planter provides a durable and attractive home for your plants. This planter exceeds industrial strength concrete with a minimum rating of 4000 psi at 28 days. Available in a wide variety of colors to fit your design needs.', model: '#PC24x30R', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC24x30R_thumb.jpg', dimensions: '24" dia x 30" tall with 2.5" wall thickness', weight: '550lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', spec: 'https://www.godawn.com/wp-content/uploads/2016/02/PC24x30R.pdf', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '2ft Square Concrete Planter', price: '$250', description: 'This concrete planter make a spacious home for plants of all sizes! Cast with a drain hole and weep channels, you can rest assured your plants will never be harmed by over watering. These concrete planters are available in a variety of colors and finishes to match any decor.', model: '#PC24x24S', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/BP-PC24x24x24S_f.jpg', dimensions: '24" cube x 18" tall with 2" tall x 2" deep toe kick at base', weight: '460lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '3ft Cylinder with Toe Kick', price: '$450', description: '3ft Cylinder Concrete Planter with Toe Kick - This concrete planter provides a durable and attractive home for your plants. This planter exceeds industrial strength concrete with a minimum rating of 4000 psi at 28 days. Available in a wide variety of colors to fit your design needs.', model: '#PC36x30R', order: '4', image: 'http://www.bigplanters.com/mm5/graphics/00000001/IMG_1218%20copy.jpg', dimensions: '36” dia x 30” tall with 2” tall x 2” deep toe kick at base', weight: '1000', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', spec: 'https://www.godawn.com/wp-content/uploads/2017/03/PC36x30R.pdf', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '3ft Round Bowl Planter', price: '$300', description: 'Our 3ft round concrete bowl planters make a lovely home for plants of all kinds! Cast with a drain hole and weep channels, you can rest assured your plants will never be harmed by over watering. They are available in a variety of colors and finishes to match any decor. Plus, due to their 600 lb weight, they can easily be used as an aesthetically pleasing form of barrier protection. ', model: '#PC36R', order: '5', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC36R_f.jpg', dimensions: '36" Dia. x 17" Height ', weight: '600lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', spec: 'https://www.godawn.com/wp-content/uploads/2017/03/PC36R.pdf', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/2017-concrete-options.pdf')

ConcretePlanter.create!(product_name: '3ft Round Concrete Deco Base', price: '$300', description: 'Our 3ft round concrete deco base bowl planters make a lovely home for plants of all kinds! Cast with a drain hole and weep channels, you can rest assured your plants will never be harmed by over watering. These concrete planters are available in a variety of colors and finishes to match any decor. Plus, due to their 600 lb weight, they can easily be used as an aesthetically pleasing form of barrier protection.', model: '#PC36RDB', order: '6', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PC36RDB_f.jpg', dimensions: '37.5" Dia. x 20" Height ', weight: '600lbs', colors: 'Natural, Charcoal, Brown, Flagstone, Padre Brown, Terra Cotta, White', finishes: 'Natural, Weathered, Light Sand Blast', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')


FiberglassPlanter.create!(product_name: 'Adamas Fiberglass Tall', price: '$206', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIDIT', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAdamas_f.jpg', dimensions: '14" Dia x 24" Height', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

FiberglassPlanter.create!(product_name: 'Athens Fiberglass Floor', price: '$120', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIATH', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAthens_f.jpg', dimensions: '14.6" L x 14.6" W x 15.2" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

FiberglassPlanter.create!(product_name: 'Athens Fiberglass Tall', price: '$173', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIDITALLFBR', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAthens_Tall_f.jpg', dimensions: '12.8" L x 12.8" W x 26.4" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

FiberglassPlanter.create!(product_name: 'Athens Fiberglass Rectangular', price: '$92', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs. ', model: '#AIART', order: '4', image: 'http://www.bigplanters.com/mm5/graphics/00000001/BPASIAthens_Rectangular_f.jpg', dimensions: '24" L x 8.75" W x 7.75" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

FiberglassPlanter.create!(product_name: 'Continental Cylinder', price: '$86', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs. ', model: '#AIEU', order: '5', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASICont_Cylinder_Small_f.jpg', dimensions: '15.5" Dia x 15" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

FiberglassPlanter.create!(product_name: 'Continental Square', price: '$152', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs. ', model: '#AIEUSQ', order: '6', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASICont_Square_Small_f.jpg', dimensions: '18" L x 18" W x 16" H', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')


PlasticPlanter.create!(product_name: 'Aqueous Plastic Self Watering', price: '$99', description: 'The new Aqueous Plastic Self Watering Planter is the perfect, carefree solution to planting indoors or outdoors. The unique design is attractive and allows water to evaporate through the soil so your plants receive the perfect amount of water automatically. Constructed from high density rotationally molded polyethylene these planters are very durable and perfect for outdoor home gardens and commercial applications. Additional colors available, call for more information.', model: '#PP27RSW', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Aqueouslarge_f.jpg', dimensions: '27" Dia x 18" Height', weight: '13lbs', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

PlasticPlanter.create!(product_name: 'Round Plastic Oasis Self Watering', price: '$169', description: 'The Oasis self watering planter is constructed of high density rotationally molded polyethylene. Empty, the plastic planter weighs only 20lbs making portability and placement quick and easy. When full, the planter weighs 300 pounds, so it will not disappear from your parking lot. This planter has capillaries between the 25gal water reservoir and the 25gal planting space that allow water to evaporate up into the soil so that your plants get the water they need, when they need it. A small spillway in the planter wall eliminates overwatering.', model: '#PP30RSW', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PP30RSW.jpg', dimensions: '27" Dia x 18" Height', weight: '20lbs', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

PlasticPlanter.create!(product_name: 'Brickell Plastic Planter', price: '$119', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#PP30RSW', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Brickell-Group-shot%20(BP).jpeg', dimensions: '27" Dia x 18" Height', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

PlasticPlanter.create!(product_name: 'Millennium Plastic Planter', price: '$600', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#TC-TSR', order: '4', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Millennium%20Straight%20Rectangular%20(BP).jpg', dimensions: '48" L x 24" W x 12" H', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

PlasticPlanter.create!(product_name: 'Half Round Plastuc Planter', price: '$139', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#TC-THR', order: '5', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Half%20Round%20Planter%20(BP).jpg', dimensions: '23.5" L x 12.5" W x 23" H', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

PlasticPlanter.create!(product_name: 'Round Plastic Pedestal', price: '$287', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#TC-TCPR', order: '6', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Round%20Pedestal%20BP.jpg', dimensions: '36" Dia x 24" H', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')


MetalPlanter.create!(product_name: 'Carnival Planter', price: '$549', description: 'The Carnival Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSCRP', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSCRP-P_f.jpg', dimensions: '29.625" Width, 27" Height ', weight: '104lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

MetalPlanter.create!(product_name: 'Cunningham Planter', price: '$729', description: 'The Cunningham Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSCNP', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSCNP-P_f.jpg', dimensions: '31.75" Width, 25.125" Height', weight: '167lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

MetalPlanter.create!(product_name: 'Genova Planter', price: '$599', description: 'The Genova Planter, made of high strength durable recycled steel, can be powder coated in a wide variety of colors. Solid construction will hold up to use and harsh weather making this planter perfect indoors and outdoors. Recycled steel planters are an eco-friendly and aesthetically appealing solution to your planting needs.', model: '#TSGNP', order: '3', image: 'http://www.bigplanters.com/mm5/graphics/00000001/TSGNP.jpg', dimensions: '24.875" Width, 17.5" Height ', weight: '144lbs', colors: 'Black, White, Gray, Blue, Green, Red, Berry, Bronze, Silver, White Metallic, Silver Metalic', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')


SelfWateringPlanter.create!(product_name: 'Aqueous Plastic Self Watering', price: '$99', description: 'The new Aqueous Plastic Self Watering Planter is the perfect, carefree solution to planting indoors or outdoors. The unique design is attractive and allows water to evaporate through the soil so your plants receive the perfect amount of water automatically. Constructed from high density rotationally molded polyethylene these planters are very durable and perfect for outdoor home gardens and commercial applications. Additional colors available, call for more information.', model: '#PP27RSW', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Aqueouslarge_f.jpg', dimensions: '27" Dia x 18" Height', weight: '13lbs', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

SelfWateringPlanter.create!(product_name: 'Round Plastic Oasis Self Watering', price: '$169', description: 'The Oasis self watering planter is constructed of high density rotationally molded polyethylene. Empty, the plastic planter weighs only 20lbs making portability and placement quick and easy. When full, the planter weighs 300 pounds, so it will not disappear from your parking lot. This planter has capillaries between the 25gal water reservoir and the 25gal planting space that allow water to evaporate up into the soil so that your plants get the water they need, when they need it. A small spillway in the planter wall eliminates overwatering.', model: '#PP30RSW', order: '2', image: 'http://www.bigplanters.com/mm5/graphics/00000001/PP30RSW.jpg', dimensions: '27" Dia x 18" Height', weight: '20lbs', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')


NewProduct.create!(product_name: 'Aqueous Plastic Self Watering', price: '$99', description: 'The new Aqueous Plastic Self Watering Planter is the perfect, carefree solution to planting indoors or outdoors. The unique design is attractive and allows water to evaporate through the soil so your plants receive the perfect amount of water automatically. Constructed from high density rotationally molded polyethylene these planters are very durable and perfect for outdoor home gardens and commercial applications. Additional colors available, call for more information.', model: '#PP27RSW', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Aqueouslarge_f.jpg', dimensions: '27" Dia x 18" Height', weight: '13lbs', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')

NewProduct.create!(product_name: 'Adamas Fiberglass Tall', price: '$206', description: 'All of our Eco-Fiberglass products have a 30% lower fossil fuel content than normal fiberglass planters. Our Eco-Fiberglass planter line offers aesthetically pleasing planters that are durable and easy to maintain. Available in a wide variety of colors and finishes to suit your design needs.
Many of our Eco-Fiberglass products are designed to include an optional sub-irrigation unit that holds a reservoir of water that evaporates up through the soil and acts as a contained self-watering planter.', model: '#AIDIT', order: '1', image: 'http://www.bigplanters.com/mm5/graphics/00000001/ASIAdamas_f.jpg', dimensions: '14" Dia x 24" Height', colors: 'Aqua, Black, Blue-Dia, Bronze, Burgundy, Burnished-Bronze, Burnished-Steel, Burnt Copper, Charcoal, Cobalt, Copper, Darksapphire, Eggplant, Expresso, G.-Quartz, Garnet, Gloss White, Gold Bronze, Gold Dust, Grey, Gunmetal, Keylime, Khaki, M.-Black, M.-White, Orange, Pearl, Pearlized-Silver, Sapphire, Scarlet, Silver, Special-Gold, Special-Red', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!', color_sheet: 'https://www.godawn.com/wp-content/uploads/2016/01/AI-Fiberglass-planter-options.pdf')

NewProduct.create!(product_name: 'Half Round Plastuc Planter', price: '$139', description: '95% lighter than concrete or stone, these plastic planters are manufactured using space age polymer resin making them the perfect durable, lightweight solution. Guaranteed not to crack, chip, or break, these planters are easy to install and light enough to significantly reduce shipping costs. These planters are easy to install and maintain, and are designed for interior and exterior applications.', model: '#TC-THR', order: '5', image: 'http://www.bigplanters.com/mm5/graphics/00000001/Half%20Round%20Planter%20(BP).jpg', dimensions: '23.5" L x 12.5" W x 23" H', additional_info: 'For additional information on this product, size options, or to request color samples please call our knowledgable sales team at 1-888-449-0542!')
